rvm:
  - 1.9.3
  - 2.0.0
matrix:
  include:
    - rvm: jruby
      env: JRUBY_OPTS="--1.9 --server -Xcext.enabled=true"
    - rvm: jruby-head
      env: JRUBY_OPTS="--1.9 --server -Xcext.enabled=true"
notifications:
  email: false
gemfile:
  - gemfiles/rails3.gemfile
  - gemfiles/rails31.gemfile
  - gemfiles/rails32.gemfile
  - gemfiles/rails4.gemfile
